version: '3.9'

services:
  mysql:
    image: bitnami/mysql:8.0.32
    ports:
      - '33450:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=2023mercedes
      - MYSQL_DATABASE=bank_app
#      - MYSQL_ALLOW_EMPTY_PASSWORD=1

volumes:
    db-data: